// packages/vue/src/components/ToolTip.tsx
import { defineComponent, ref } from 'vue'
import '../assets/css/tooltip.scss'

export default defineComponent({
  name: 'ToolTip',
  setup(_, { slots }) {
    const visible = ref<boolean>(false)
    const visible2 = ref<boolean>(false)
    const onMouseEnter = (e: MouseEvent, type: string) => {
      e.stopPropagation()
      if (type === 'content') {
        visible2.value = true
      }
      visible.value = true
    }
    const onMouseLeave = (e: MouseEvent, type: string) => {
      e.stopPropagation()
      if (type === 'main') {
        setTimeout(() => {
          if (!visible2.value) {
            visible.value = false
          }
        }, 500)
      } else if (type === 'content') {
        visible2.value = false
        visible.value = false
      }
    }
    return () => (
      <div class="tooltip-wrapper">
        <div
          onMouseenter={(e) => onMouseEnter(e, 'main')}
          onMouseleave={(e) => onMouseLeave(e, 'main')}
        >
          {slots.default?.()}
        </div>
        <div
          class={['tooltip-content', visible.value ? 'mouse-in' : '']}
          onMouseenter={(e) => onMouseEnter(e, 'content')}
          onMouseleave={(e) => onMouseLeave(e, 'content')}
        >
          {slots.content?.()}
        </div>
      </div>
    )
  },
})

// packages/react/src/components/ToolTip.tsx
import { useState, useRef, ReactNode, MouseEvent } from 'react'
import * as  PropTypes from 'prop-types'
import classnames from 'classnames'
import '../assets/css/tooltip.scss'

export interface ToolTipProps {
  children?: Array<ReactNode>
  content?: string
}

function ToolTip({ children, content }: ToolTipProps) {
  const [visible, setVisible] = useState(false)
  const visible2 = useRef(false)
  const handleMouseEnter = (e: MouseEvent, type: string) => {
    e.stopPropagation()
    if (type === 'content') {
      visible2.current = true
    }
    setVisible(true)
  }
  const handleMouseLeave = (e: MouseEvent, type: string) => {
    e.stopPropagation()
    if (type === 'main') {
      setTimeout(() => {
        if (!visible2.current) {
          setVisible(false)
        }
      }, 500)
    } else if (type === 'content') {
      visible2.current = false
      setVisible(false)
    }
  }
  return (
    <div className="tooltip-wrapper">
      <div onMouseEnter={(e) => handleMouseEnter(e, 'main')} onMouseLeave={(e) => handleMouseLeave(e, 'main')}>
        {Array.isArray(children) ? children[0] : children}
      </div>
      <div
        className={classnames('tooltip-content', visible ? 'mouse-in' : '')}
        onMouseEnter={(e) => handleMouseEnter(e, 'content')}
        onMouseLeave={(e) => handleMouseLeave(e, 'content')}
      >
        {content || (Array.isArray(children) && children[1])}
      </div>
    </div>
  )
}

ToolTip.propTypes = {
  children: PropTypes.array,
  content: PropTypes.string,
}

export default ToolTip
