// packages/react/src/components/ToolBar.tsx
import { TOOLBAR_CONFIG } from '@simple-m-editor/constants'
import * as PropTypes from 'prop-types'
import ToolTip from './ToolTip'
import '../assets/css/icon.css'
import '../assets/css/toolbar.scss'

import classnames from 'classnames'

export interface ToolBarProps {
  fullScreen: boolean
  mode: string
  iconLength: number
  appendContent: (content?: string) => void
  fullScreenChange: (isFullScreen: boolean) => void
  modeChange: (newMode: string) => void
}

const modeConfig = [
  {
    mode: 'edit',
    title: '编辑',
    icon: 'icon-tianxie',
  },
  {
    mode: 'live',
    title: '分栏',
    icon: 'icon-fenlan',
  },
  {
    mode: 'preview',
    title: '预览',
    icon: 'icon-zitiyulan',
  },
]

function Toolbar(props: ToolBarProps) {
  const { fullScreen, fullScreenChange, modeChange, mode, iconLength, appendContent } = props
  return (
    <div className="editor-toolbar">
      <ul className="editor-toolbar-tools">
        {TOOLBAR_CONFIG.map((item, key) => {
          return item.showIcon && key < iconLength ? (
            <li key={key}>
              {item.children && item.children.length ? (
                <ToolTip>
                  <span
                    className={classnames('iconfont', item.icon)}
                    title={item.title}
                  />
                  <div>
                    {item.children.map((_item, j) => (
                      <div key={j}>
                        <span
                          style={{ fontSize: `${_item.size}px` }}
                          title={_item.title}
                          onClick={() => {
                            appendContent(_item.content)
                          }}
                        >
                          {_item.text}
                        </span>
                      </div>
                    ))}
                  </div>
                </ToolTip>
              ) : (
                <span
                  className={classnames('iconfont', item.icon)}
                  title={item.title}
                  onClick={() => {
                    appendContent(item.content)
                  }}
                />
              )}
            </li>
          ) : null
        })}
      </ul>
      <ul className="editor-toolbar-mode">
        <li>
          <span
            className={classnames('iconfont', !fullScreen ? 'icon-quanping' : 'icon-huanyuanhuabu')}
            title={!fullScreen ? '全屏' : '还原'}
            onClick={() => {
              fullScreenChange(!fullScreen)
            }}
          />
        </li>
        {modeConfig.map((item, i) => (
          <li key={i}>
            <span
              className={classnames('iconfont', item.icon, mode === item.mode && 'muted')}
              onClick={() => {
                modeChange(item.mode)
              }}
            />
          </li>
        ))}
      </ul>
    </div>
  )
}
Toolbar.propTypes = {
  fullScreen: PropTypes.bool,
  mode: PropTypes.string,
  iconLength: PropTypes.number,
  appendContent: PropTypes.func,
  fullScreenChange: PropTypes.func,
  modeChange: PropTypes.func,
}

export default Toolbar

// packages/vue/src/components/ToolBar.tsx
import { defineComponent, toRefs } from 'vue'
import { TOOLBAR_CONFIG, EditorToolbarConfigItem } from '@simple-m-editor/constants'
import ToolTip from './ToolTip'
import '../assets/css/icon.css'
import '../assets/css/toolbar.scss'

const modeConfig = [
  {
    mode: 'edit',
    title: '编辑',
    icon: 'icon-tianxie',
  },
  {
    mode: 'live',
    title: '分栏',
    icon: 'icon-fenlan',
  },
  {
    mode: 'preview',
    title: '预览',
    icon: 'icon-zitiyulan',
  },
]
export default defineComponent({
  name: 'Toolbar',
  components: {
    ToolTip,
  },
  props: {
    fullScreen: {
      type: Boolean,
      default: false,
    },
    mode: {
      type: String,
      default: 'live',
    },
    iconLength: {
      type: Number,
      required: true,
    },
  },
  emits: ['mode-change', 'append-content', 'fullscreen-change'],
  setup(props, { emit }) {
    const { fullScreen, mode, iconLength } = toRefs(props)

    const appendContent = (content: string) => {
      emit('append-content', content)
    }
    const fullScreenChange = (fullScreen: boolean) => {
      emit('fullscreen-change', fullScreen)
    }
    const modeChange = (_mode: string) => {
      if (_mode !== mode.value) {
        emit('mode-change', _mode, mode.value)
      }
    }
    const toolTipSlots = (item: EditorToolbarConfigItem) => ({
      default: () => (
        <span
          className={['iconfont', item.icon]}
          title={item.title}
        />
      ),
      content: () =>
        item.children?.map((_item, j) => (
          <div key={j}>
            <span
              style={{ fontSize: `${_item.size}px` }}
              title={_item.title}
              onClick={() => appendContent(_item.content)}
            >
              {_item.text}
            </span>
          </div>
        )),
    })
    return () => (
      <div class="editor-toolbar">
        <ul class="editor-toolbar-tools">
          {TOOLBAR_CONFIG.map((item, key) => {
            return item.showIcon && key < iconLength.value ? (
              <li key={key}>
                {item.children && item.children.length ? (
                  <ToolTip v-slots={toolTipSlots(item)} />
                ) : (
                  <span
                    class={['iconfont', item.icon]}
                    title={item.title}
                    onClick={() => appendContent(item.content as string)}
                  />
                )}
              </li>
            ) : null
          })}
        </ul>
        <ul class="editor-toolbar-mode">
          <li>
            <span
              class={['iconfont', !fullScreen.value ? 'icon-quanping' : 'icon-huanyuanhuabu']}
              title={!fullScreen.value ? '全屏' : '还原'}
              onClick={() => fullScreenChange(!fullScreen.value)}
            />
          </li>
          {modeConfig.map((item, i) => (
            <li key={i}>
              <span
                class={['iconfont', item.icon, mode.value === item.mode && 'muted']}
                onClick={() => modeChange(item.mode)}
              />
            </li>
          ))}
        </ul>
      </div>
    )
  },
})
